//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class AQL_ORDER
    {
        public long ID { get; set; }
        public long OPTION_ID { get; set; }
        public int SEASON_ID { get; set; }
        public int SALES_CHANNE_ID { get; set; }
        public int QTY { get; set; }
        public Nullable<System.DateTime> FS_DATE { get; set; }
        public Nullable<int> MIN_S_QTY { get; set; }
        public Nullable<int> MAX_S_QTY { get; set; }
    }
}
