//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTHORIZATION_GROUP
    {
        public int ID { get; set; }
        public string TITLE { get; set; }
        public string GROUP_TABLE_NAME { get; set; }
        public string GROUP_ID_FIELD_NAME { get; set; }
        public string GROUP_DESC_FIELD_NAME { get; set; }
    }
}
