//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTHORIZATION_MENUITEM
    {
        public long ID { get; set; }
        public string CAPTION { get; set; }
        public string MENUCODE { get; set; }
    }
}
