//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTHORIZATION_CROSS
    {
        public long ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> AUTHORIZATION_GROUP_ID { get; set; }
        public Nullable<long> GROUP_TABLE_ID { get; set; }
        public Nullable<bool> AUTHORITY { get; set; }
    }
}
