//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUDGET_PAR_GROUP
    {
        public int ID { get; set; }
        public string ACIKLAMA { get; set; }
        public int GRUP { get; set; }
        public string ACIKLAMA1 { get; set; }
    }
}
