//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUDGET_LINK_MASTER
    {
        public int ID { get; set; }
        public int BASLIK_ID { get; set; }
        public int REVIZYON_ID { get; set; }
        public int LINK_BASLIK_ID { get; set; }
        public int LINK_REVIZYON_ID { get; set; }
    }
}
