//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUDGET_DETAIL_UNIT
    {
        public long ID { get; set; }
        public int BASLIK_ID { get; set; }
        public int DETAY_DONEM_SIRA_ID { get; set; }
        public int DETAY_SIRA_ID { get; set; }
        public int REVIZYON_ID { get; set; }
        public int DEGERLER_ID { get; set; }
        public double DEGER { get; set; }
        public double DEGER_OD { get; set; }
        public double DEGER_GD { get; set; }
        public string KUL_NOTU { get; set; }
        public int PARGRUP_ID { get; set; }
        public double PAR1 { get; set; }
        public double PAR2 { get; set; }
        public double PAR3 { get; set; }
        public int RENK_ID { get; set; }
        public double FORMUL_SONUC { get; set; }
    }
}
