//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUDGET_HIERARCHY
    {
        public int ID { get; set; }
        public string TABLE_NAME { get; set; }
        public string FIELD_NAME { get; set; }
        public string CAPTION { get; set; }
        public string GROUP_NAME { get; set; }
        public int BUTCE_TIPI { get; set; }
        public string ID_FIELDNAME { get; set; }
    }
}
