//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUDGET_MASTER
    {
        public int ID { get; set; }
        public string ADI { get; set; }
        public int BUTCE_TIPI { get; set; }
        public System.DateTime BAS_TAR { get; set; }
        public System.DateTime BIT_TAR { get; set; }
        public int DONEM { get; set; }
        public bool MERCH_TARIH { get; set; }
        public string HIYERARSI { get; set; }
        public string DEGERLER { get; set; }
        public string HIYERARSI_SQL { get; set; }
        public Nullable<int> SIRKET_NO { get; set; }
        public int FORMUL_DEGERID { get; set; }
        public System.DateTime EKLEME_TARIHI { get; set; }
        public int OD_HESAPLAMA_TIPI { get; set; }
        public int SEZON_ID { get; set; }
        public int BUTCE_DURUM { get; set; }
        public int DONEM_TIP { get; set; }
    }
}
