//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUDGET_REPORT_LINK
    {
        public int ID { get; set; }
        public int KAYNAK_BUTCE_ID { get; set; }
        public int KAYNAK_REV_ID { get; set; }
        public int LINK_BUTCE_ID { get; set; }
        public int LINK_REV_ID { get; set; }
        public int LINK_TURU { get; set; }
    }
}
