//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUDGET_REVISION
    {
        public int ID { get; set; }
        public int BASLIK_ID { get; set; }
        public int REVIZYON_ID { get; set; }
        public string ACIKLAMA { get; set; }
        public System.DateTime OTARIH { get; set; }
        public int PARAM_GRUP_ID { get; set; }
        public int DURUM { get; set; }
    }
}
