//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUDGET_DETAIL
    {
        public int ID { get; set; }
        public int BASLIK_ID { get; set; }
        public int SIRA_ID { get; set; }
        public int KIRILIM_ID { get; set; }
        public string BOYUT_ADI { get; set; }
        public int KIRILIMDB_ID { get; set; }
        public string KIRILIM_INDEX { get; set; }
        public int DUZEY_ID { get; set; }
        public int ROOT_ID { get; set; }
        public int KUL_SIRA_ID { get; set; }
        public string KIRILIMDB_INDEX { get; set; }
    }
}
