//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALENDAR_YEDEK4
    {
        public long ID { get; set; }
        public long COUNTRY_ID { get; set; }
        public long COMPANY_ID { get; set; }
        public System.DateTime DATE { get; set; }
        public Nullable<short> YEAR { get; set; }
        public Nullable<short> MONTH { get; set; }
        public string MONTH_NAME { get; set; }
        public Nullable<short> WEEK { get; set; }
        public Nullable<short> DAY { get; set; }
        public string DAY_NAME { get; set; }
        public string QUARTER { get; set; }
        public string SEMESTER { get; set; }
        public Nullable<System.DateTime> LFL_DATE { get; set; }
        public Nullable<short> MERCH_YEAR { get; set; }
        public Nullable<short> MERCH_MONTH { get; set; }
        public string MERCH_MONTH_NAME { get; set; }
        public Nullable<short> MERCH_WEEK { get; set; }
        public Nullable<short> MERCH_DAY { get; set; }
        public string MERCH_QUARTER { get; set; }
        public string MERCH_SEMESTER { get; set; }
        public Nullable<long> MERCH_YEAR_WEEK { get; set; }
        public Nullable<long> YEAR_WEEK { get; set; }
        public Nullable<long> OLD_ID { get; set; }
        public Nullable<long> NEW_ID { get; set; }
    }
}
