//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANNEL_PLAN
    {
        public long ID { get; set; }
        public Nullable<long> MASTER_ID { get; set; }
        public Nullable<long> CHN_PLAN_HY_DETAIL_ID { get; set; }
        public Nullable<long> START_CALENDAR_ID { get; set; }
        public Nullable<long> END_CALENDAR_ID { get; set; }
        public Nullable<decimal> TY_SALES_AMOUNT_WO_VAT { get; set; }
        public Nullable<decimal> TY_SALES_QTY { get; set; }
        public Nullable<decimal> TY_SALES_PROFIT { get; set; }
        public Nullable<decimal> TY_SALES_ISP_WO_VAT { get; set; }
        public Nullable<decimal> TY_PROFIT_MARGIN { get; set; }
        public Nullable<decimal> TY_DISCOUNT_RATE { get; set; }
        public Nullable<decimal> TY_AVG_PRICE { get; set; }
        public Nullable<decimal> TY_AVG_MARKUP { get; set; }
        public Nullable<decimal> TY_INV_TURNOVER { get; set; }
        public Nullable<decimal> CS_SALES_AMOUNT_WO_VAT { get; set; }
        public Nullable<decimal> CS_SALES_QTY { get; set; }
        public Nullable<decimal> CS_SALES_PROFIT { get; set; }
        public Nullable<decimal> CS_SALES_ISP_WO_VAT { get; set; }
        public Nullable<decimal> CS_PROFIT_MARGIN { get; set; }
        public Nullable<decimal> CS_DISCOUNT_RATE { get; set; }
        public Nullable<decimal> CS_AVG_PRICE { get; set; }
        public Nullable<decimal> CS_AVG_MARKUP { get; set; }
        public Nullable<decimal> CS_INV_TURNOVER { get; set; }
    }
}
