//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSUMPTION_MASTER
    {
        public long ID { get; set; }
        public long SUPPLIER_ID { get; set; }
        public int SEASON_ID { get; set; }
    }
}
