//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class COS_DAILY_EFFECT
    {
        public long ID { get; set; }
        public long COUNTRY_ID { get; set; }
        public long CALENDAR_ID { get; set; }
        public decimal DAILY_SALES_EFFECT { get; set; }
        public bool VISIBLE { get; set; }
    }
}
