//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class DST_DETAIL
    {
        public long ID { get; set; }
        public long MASTER_ID { get; set; }
        public long PRODUCT_ID { get; set; }
        public long ASORTI_ID { get; set; }
        public long ASORTI_DETAIL_ID { get; set; }
        public long SOURCE_WH_ID { get; set; }
        public long TARGET_WH_ID { get; set; }
        public int QTY { get; set; }
        public Nullable<long> OPTION_ID { get; set; }
    }
}
