//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class DST_MASTER
    {
        public long ID { get; set; }
        public string DESCRIPTION { get; set; }
        public long CALENDAR_ID { get; set; }
        public bool CONFIRMATION { get; set; }
        public string FILTERS { get; set; }
        public short DST_TYPE { get; set; }
        public short METHOD { get; set; }
        public string SOURCE_WH_IDS { get; set; }
        public string TARGET_WH_IDS { get; set; }
        public string PRODUCT_ID { get; set; }
        public int SOURCE_MIN_QTY { get; set; }
        public bool DST_ALL { get; set; }
        public int DST_QTY { get; set; }
        public string SORTING { get; set; }
    }
}
