//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class DST_FILTERS
    {
        public long ID { get; set; }
        public long MASTER_ID { get; set; }
        public short FILTER_TYPE { get; set; }
        public string FIELD_NAME { get; set; }
        public Nullable<short> FIELD_NAME_ID { get; set; }
        public Nullable<short> TRS_OP_ID { get; set; }
        public Nullable<double> VALUE { get; set; }
        public Nullable<System.DateTime> VALUE_DATE { get; set; }
        public int SOURCE { get; set; }
    }
}
