//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class DST_LOG
    {
        public long ID { get; set; }
        public long MASTER_ID { get; set; }
        public long WH_ID { get; set; }
        public long PRODUCT_ID { get; set; }
        public int AVL_QTY { get; set; }
        public int RQS_QTY { get; set; }
        public int ACT_QTY { get; set; }
    }
}
