//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENUM_DETAIL
    {
        public long ID { get; set; }
        public string CODE { get; set; }
        public Nullable<long> MASTER_ID { get; set; }
        public Nullable<long> VALUE_ID { get; set; }
        public string VALUE_DISPLAY { get; set; }
    }
}
