//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENUM_MASTER
    {
        public long ID { get; set; }
        public string CODE { get; set; }
        public string ATTRIBUTE { get; set; }
        public string DISPLAY_NAME { get; set; }
        public Nullable<long> ENUM_TYPE { get; set; }
        public string ENUM_TABLE_NAME { get; set; }
        public string ENUM_FIELD_NAME { get; set; }
    }
}
