//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY_ONWAY
    {
        public long ID { get; set; }
        public long WH_ID { get; set; }
        public long PRODUCT_ID { get; set; }
        public long ASORTI_ID { get; set; }
        public Nullable<long> SEASON_ID { get; set; }
        public Nullable<decimal> INV { get; set; }
        public Nullable<decimal> ISP { get; set; }
        public Nullable<decimal> ISP_WO_VAT { get; set; }
        public Nullable<decimal> COST { get; set; }
    }
}
