//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL_PRODUCT
    {
        public long ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public Nullable<long> OPTION_ID { get; set; }
        public Nullable<long> SIZE_ID { get; set; }
        public string INFO1 { get; set; }
        public string INFO2 { get; set; }
        public string INFO3 { get; set; }
    }
}
