//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL_SIZE_QTY
    {
        public long ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<long> SEASON_ID { get; set; }
        public Nullable<long> ENUM_MASTER1_ID { get; set; }
        public Nullable<long> ENUM_VALUE1_ID { get; set; }
        public Nullable<long> ENUM_MASTER2_ID { get; set; }
        public Nullable<long> ENUM_VALUE2_ID { get; set; }
        public Nullable<long> ENUM_MASTER3_ID { get; set; }
        public Nullable<long> ENUM_VALUE3_ID { get; set; }
        public Nullable<long> SIZE_ID { get; set; }
        public Nullable<int> MIN_QTY { get; set; }
        public Nullable<int> MAX_QTY { get; set; }
        public Nullable<int> OPT_QTY { get; set; }
    }
}
