//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL_STYLE
    {
        public long ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<long> MAINGROUP_ID { get; set; }
        public Nullable<long> SUBGROUP_ID { get; set; }
        public Nullable<long> CATEGORY_ID { get; set; }
        public Nullable<long> GENDER_ID { get; set; }
        public Nullable<long> BRAND_ID { get; set; }
        public Nullable<long> PRODUCTTYPE_ID { get; set; }
        public Nullable<long> CLASS_ID { get; set; }
        public Nullable<long> MODEL_ID { get; set; }
        public Nullable<long> DIVISION_ID { get; set; }
        public Nullable<long> SUBDIVISION_ID { get; set; }
        public Nullable<long> BUYERGROUP_ID { get; set; }
        public Nullable<long> MERCHGROUP_ID { get; set; }
        public Nullable<long> MERCHSUBGROUP_ID { get; set; }
        public Nullable<long> FABRIC_ID { get; set; }
        public Nullable<long> SEASON_ID { get; set; }
        public Nullable<long> ATTRIBUTE1_ID { get; set; }
        public Nullable<long> ATTRIBUTE2_ID { get; set; }
        public Nullable<long> ATTRIBUTE3_ID { get; set; }
        public Nullable<long> ATTRIBUTE4_ID { get; set; }
        public Nullable<long> ATTRIBUTE5_ID { get; set; }
        public Nullable<long> ATTRIBUTE6_ID { get; set; }
        public Nullable<long> ATTRIBUTE7_ID { get; set; }
        public Nullable<long> ATTRIBUTE8_ID { get; set; }
        public Nullable<long> ATTRIBUTE9_ID { get; set; }
        public Nullable<long> ATTRIBUTE10_ID { get; set; }
        public Nullable<long> ATTRIBUTE11_ID { get; set; }
        public Nullable<long> ATTRIBUTE12_ID { get; set; }
        public Nullable<long> ATTRIBUTE13_ID { get; set; }
        public Nullable<long> ATTRIBUTE14_ID { get; set; }
        public Nullable<long> ATTRIBUTE15_ID { get; set; }
        public Nullable<long> ATTRIBUTE16_ID { get; set; }
        public Nullable<long> ATTRIBUTE17_ID { get; set; }
        public Nullable<long> ATTRIBUTE18_ID { get; set; }
        public Nullable<long> ATTRIBUTE19_ID { get; set; }
        public Nullable<long> ATTRIBUTE20_ID { get; set; }
        public Nullable<long> SUBCATEGORY_ID { get; set; }
        public Nullable<long> PRICEGROUP_ID { get; set; }
    }
}
