//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL_SKU
    {
        public long ID { get; set; }
        public string CODE { get; set; }
        public long PRODUCT_ID { get; set; }
        public string BARCODE { get; set; }
        public Nullable<long> TEDARIKCI_ID { get; set; }
        public Nullable<long> SIPARIS_ID { get; set; }
        public Nullable<long> PARTINO { get; set; }
    }
}
