//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataPortDessEntities : DbContext
    {
        public DataPortDessEntities()
            : base("name=DataPortDessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BUDGET_DETAIL> BUDGET_DETAIL { get; set; }
        public virtual DbSet<BUDGET_DETAIL_PERIOD> BUDGET_DETAIL_PERIOD { get; set; }
        public virtual DbSet<BUDGET_DETAIL_TYPE> BUDGET_DETAIL_TYPE { get; set; }
        public virtual DbSet<BUDGET_DETAIL_UNIT> BUDGET_DETAIL_UNIT { get; set; }
        public virtual DbSet<BUDGET_HIERARCHY> BUDGET_HIERARCHY { get; set; }
        public virtual DbSet<BUDGET_LINK_DETAIL> BUDGET_LINK_DETAIL { get; set; }
        public virtual DbSet<BUDGET_LINK_MASTER> BUDGET_LINK_MASTER { get; set; }
        public virtual DbSet<BUDGET_MASTER> BUDGET_MASTER { get; set; }
        public virtual DbSet<BUDGET_MASTER_FILTERS> BUDGET_MASTER_FILTERS { get; set; }
        public virtual DbSet<BUDGET_MEASURE_FORMUL> BUDGET_MEASURE_FORMUL { get; set; }
        public virtual DbSet<BUDGET_MEASURES> BUDGET_MEASURES { get; set; }
        public virtual DbSet<BUDGET_PAR_FORMUL> BUDGET_PAR_FORMUL { get; set; }
        public virtual DbSet<BUDGET_PAR_GROUP> BUDGET_PAR_GROUP { get; set; }
        public virtual DbSet<BUDGET_REPORT_LINK> BUDGET_REPORT_LINK { get; set; }
        public virtual DbSet<BUDGET_REVISION> BUDGET_REVISION { get; set; }
        public virtual DbSet<COS_DAILY_EFFECT> COS_DAILY_EFFECT { get; set; }
        public virtual DbSet<COS_DETAIL> COS_DETAIL { get; set; }
        public virtual DbSet<COS_EXC_DAILY_EFFECT> COS_EXC_DAILY_EFFECT { get; set; }
        public virtual DbSet<COS_MASTER> COS_MASTER { get; set; }
        public virtual DbSet<COMPONENT_TYPE> COMPONENT_TYPE { get; set; }
        public virtual DbSet<COMPONENTS> COMPONENTS { get; set; }
        public virtual DbSet<HIE_DETAIL> HIE_DETAIL { get; set; }
        public virtual DbSet<HIE_MASTER> HIE_MASTER { get; set; }
        public virtual DbSet<PRO_MEASUREMENT_DETAIL> PRO_MEASUREMENT_DETAIL { get; set; }
        public virtual DbSet<PRO_MEASUREMENT_MASTER> PRO_MEASUREMENT_MASTER { get; set; }
        public virtual DbSet<RULE> RULE { get; set; }
        public virtual DbSet<RULE_DETAIL> RULE_DETAIL { get; set; }
        public virtual DbSet<SPLITTINGRULE_DETAIL> SPLITTINGRULE_DETAIL { get; set; }
        public virtual DbSet<SPLITTINGRULE_MASTER> SPLITTINGRULE_MASTER { get; set; }
        public virtual DbSet<UNIT_COMPONENTS> UNIT_COMPONENTS { get; set; }
        public virtual DbSet<UNIT_TYPE> UNIT_TYPE { get; set; }
        public virtual DbSet<UNITASSIGMENT_DETAIL> UNITASSIGMENT_DETAIL { get; set; }
        public virtual DbSet<UNITASSIGMENT_MASTER> UNITASSIGMENT_MASTER { get; set; }
        public virtual DbSet<UNITS> UNITS { get; set; }
        public virtual DbSet<INVENTORY_WMS> INVENTORY_WMS { get; set; }
        public virtual DbSet<SHIPMENT_TYPE> SHIPMENT_TYPE { get; set; }
        public virtual DbSet<SHIPMENTS> SHIPMENTS { get; set; }
        public virtual DbSet<ACCOUNT> ACCOUNT { get; set; }
        public virtual DbSet<AUTHORIZATION_CROSS> AUTHORIZATION_CROSS { get; set; }
        public virtual DbSet<AUTHORIZATION_GROUP> AUTHORIZATION_GROUP { get; set; }
        public virtual DbSet<AUTHORIZATION_MENUITEM> AUTHORIZATION_MENUITEM { get; set; }
        public virtual DbSet<CALENDAR> CALENDAR { get; set; }
        public virtual DbSet<COMPANY> COMPANY { get; set; }
        public virtual DbSet<COUNTRY> COUNTRY { get; set; }
        public virtual DbSet<DOCUMENT> DOCUMENT { get; set; }
        public virtual DbSet<ENUM_DETAIL> ENUM_DETAIL { get; set; }
        public virtual DbSet<ENUM_MASTER> ENUM_MASTER { get; set; }
        public virtual DbSet<GENERAL_SETTINGS> GENERAL_SETTINGS { get; set; }
        public virtual DbSet<GROUP_DETAIL> GROUP_DETAIL { get; set; }
        public virtual DbSet<GROUP_MASTER> GROUP_MASTER { get; set; }
        public virtual DbSet<INVENTORY> INVENTORY { get; set; }
        public virtual DbSet<INVENTORY_CURRENT> INVENTORY_CURRENT { get; set; }
        public virtual DbSet<INVENTORY_FORECAST> INVENTORY_FORECAST { get; set; }
        public virtual DbSet<INVENTORY_ONWAY> INVENTORY_ONWAY { get; set; }
        public virtual DbSet<MATERIAL_ASORTI_BARCODE> MATERIAL_ASORTI_BARCODE { get; set; }
        public virtual DbSet<MATERIAL_ASORTI_DETAIL> MATERIAL_ASORTI_DETAIL { get; set; }
        public virtual DbSet<MATERIAL_ASORTI_MASTER> MATERIAL_ASORTI_MASTER { get; set; }
        public virtual DbSet<MATERIAL_COLOR> MATERIAL_COLOR { get; set; }
        public virtual DbSet<MATERIAL_OPTION> MATERIAL_OPTION { get; set; }
        public virtual DbSet<MATERIAL_PRODUCT> MATERIAL_PRODUCT { get; set; }
        public virtual DbSet<MATERIAL_SIZE> MATERIAL_SIZE { get; set; }
        public virtual DbSet<MATERIAL_SIZE_QTY> MATERIAL_SIZE_QTY { get; set; }
        public virtual DbSet<MATERIAL_SKU> MATERIAL_SKU { get; set; }
        public virtual DbSet<MATERIAL_STYLE> MATERIAL_STYLE { get; set; }
        public virtual DbSet<ORDER_SUMM> ORDER_SUMM { get; set; }
        public virtual DbSet<PRODUCT_LIFE> PRODUCT_LIFE { get; set; }
        public virtual DbSet<PRODUCT_LIFE_MASTER> PRODUCT_LIFE_MASTER { get; set; }
        public virtual DbSet<RAPOR_INFO> RAPOR_INFO { get; set; }
        public virtual DbSet<SALES> SALES { get; set; }
        public virtual DbSet<SALES_ACCOUNT_SUMM> SALES_ACCOUNT_SUMM { get; set; }
        public virtual DbSet<SALES_CHANNEL> SALES_CHANNEL { get; set; }
        public virtual DbSet<SEASON> SEASON { get; set; }
        public virtual DbSet<SEASON_DETAIL> SEASON_DETAIL { get; set; }
        public virtual DbSet<SEASON_SUMM> SEASON_SUMM { get; set; }
        public virtual DbSet<SO_DETAIL> SO_DETAIL { get; set; }
        public virtual DbSet<SO_MASTER> SO_MASTER { get; set; }
        public virtual DbSet<STORE> STORE { get; set; }
        public virtual DbSet<SUPPLIER> SUPPLIER { get; set; }
        public virtual DbSet<SUPPLY_CHANNEL> SUPPLY_CHANNEL { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<WH> WH { get; set; }
        public virtual DbSet<AQL_ORDER> AQL_ORDER { get; set; }
        public virtual DbSet<CONSTRAINT_DETAIL> CONSTRAINT_DETAIL { get; set; }
        public virtual DbSet<CONSTRAINT_MASTER> CONSTRAINT_MASTER { get; set; }
        public virtual DbSet<DST_DETAIL> DST_DETAIL { get; set; }
        public virtual DbSet<DST_FILTERS> DST_FILTERS { get; set; }
        public virtual DbSet<DST_LOG> DST_LOG { get; set; }
        public virtual DbSet<DST_MASTER> DST_MASTER { get; set; }
        public virtual DbSet<SALES_FACTOR> SALES_FACTOR { get; set; }
        public virtual DbSet<SENDING_LIMIT_DETAIL> SENDING_LIMIT_DETAIL { get; set; }
        public virtual DbSet<SENDING_LIMIT_MASTER> SENDING_LIMIT_MASTER { get; set; }
        public virtual DbSet<STR_PHYSICAL_CPC> STR_PHYSICAL_CPC { get; set; }
        public virtual DbSet<STR_PHYSICAL_CPC_MASTER> STR_PHYSICAL_CPC_MASTER { get; set; }
        public virtual DbSet<STRMTR_COM> STRMTR_COM { get; set; }
        public virtual DbSet<STRPRI_DETAIL> STRPRI_DETAIL { get; set; }
        public virtual DbSet<STRPRI_MASTER> STRPRI_MASTER { get; set; }
        public virtual DbSet<STRSIZE_LIMIT> STRSIZE_LIMIT { get; set; }
        public virtual DbSet<PR_WEEK_GROWTH> PR_WEEK_GROWTH { get; set; }
        public virtual DbSet<STORE_RATE> STORE_RATE { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<Translations> Translations { get; set; }
        public virtual DbSet<CATEGORY_PLAN> CATEGORY_PLAN { get; set; }
        public virtual DbSet<CHANNEL_PLAN> CHANNEL_PLAN { get; set; }
        public virtual DbSet<PLAN_MASTER> PLAN_MASTER { get; set; }
        public virtual DbSet<PLAN_TYPE> PLAN_TYPE { get; set; }
        public virtual DbSet<CONSUMPTION_DETAIL> CONSUMPTION_DETAIL { get; set; }
        public virtual DbSet<CONSUMPTION_MASTER> CONSUMPTION_MASTER { get; set; }
        public virtual DbSet<MOVEMENT_DETAIL> MOVEMENT_DETAIL { get; set; }
        public virtual DbSet<MOVEMENT_MASTER> MOVEMENT_MASTER { get; set; }
        public virtual DbSet<PATH_ASSIGN_DETAIL> PATH_ASSIGN_DETAIL { get; set; }
        public virtual DbSet<PATH_ASSIGN_MASTER> PATH_ASSIGN_MASTER { get; set; }
        public virtual DbSet<PATH_DETAIL> PATH_DETAIL { get; set; }
        public virtual DbSet<PATH_MASTER> PATH_MASTER { get; set; }
        public virtual DbSet<PHASE> PHASE { get; set; }
        public virtual DbSet<PLAN> PLAN { get; set; }
        public virtual DbSet<PLAN_YEDEK> PLAN_YEDEK { get; set; }
        public virtual DbSet<PO_DETAIL> PO_DETAIL { get; set; }
        public virtual DbSet<PO_MASTER> PO_MASTER { get; set; }
        public virtual DbSet<QC_INLINE_DETAIL> QC_INLINE_DETAIL { get; set; }
        public virtual DbSet<QC_INLINE_MASTER> QC_INLINE_MASTER { get; set; }
        public virtual DbSet<QC_PREFERENCE> QC_PREFERENCE { get; set; }
        public virtual DbSet<QC_STYLETEST_DETAIL> QC_STYLETEST_DETAIL { get; set; }
        public virtual DbSet<QC_STYLETEST_MASTER> QC_STYLETEST_MASTER { get; set; }
        public virtual DbSet<QC_TEST_ASSIGN_DETAIL> QC_TEST_ASSIGN_DETAIL { get; set; }
        public virtual DbSet<QC_TEST_ASSIGN_MASTER> QC_TEST_ASSIGN_MASTER { get; set; }
        public virtual DbSet<QC_TEST_DETAIL> QC_TEST_DETAIL { get; set; }
        public virtual DbSet<QC_TEST_DETAIL_DETAIL> QC_TEST_DETAIL_DETAIL { get; set; }
        public virtual DbSet<QC_TEST_MASTER> QC_TEST_MASTER { get; set; }
        public virtual DbSet<QC_TESTER> QC_TESTER { get; set; }
        public virtual DbSet<QC_TESTINFO_DETAIL> QC_TESTINFO_DETAIL { get; set; }
        public virtual DbSet<QC_TESTINFO_MASTER> QC_TESTINFO_MASTER { get; set; }
        public virtual DbSet<SAFHA> SAFHA { get; set; }
        public virtual DbSet<SUPPLIER_BUFFER_TIME> SUPPLIER_BUFFER_TIME { get; set; }
        public virtual DbSet<SUPPLIER_WEEKLY_CAPASITY> SUPPLIER_WEEKLY_CAPASITY { get; set; }
        public virtual DbSet<TS_ACCESSORY> TS_ACCESSORY { get; set; }
        public virtual DbSet<TS_COLOR> TS_COLOR { get; set; }
        public virtual DbSet<TS_COLOR_LIBRARY> TS_COLOR_LIBRARY { get; set; }
        public virtual DbSet<TS_ETL> TS_ETL { get; set; }
        public virtual DbSet<TS_FABRICS> TS_FABRICS { get; set; }
        public virtual DbSet<TS_INSTRUCTION> TS_INSTRUCTION { get; set; }
        public virtual DbSet<TS_MODELS> TS_MODELS { get; set; }
        public virtual DbSet<TS_PACKAGE> TS_PACKAGE { get; set; }
        public virtual DbSet<TS_SIZE> TS_SIZE { get; set; }
        public virtual DbSet<TS_VARIANT> TS_VARIANT { get; set; }
        public virtual DbSet<DESS_QC_STYLETEST_DETAIL> DESS_QC_STYLETEST_DETAIL { get; set; }
        public virtual DbSet<DESS_QC_STYLETEST_MASTER> DESS_QC_STYLETEST_MASTER { get; set; }
        public virtual DbSet<CALENDAR_YEDEK> CALENDAR_YEDEK { get; set; }
        public virtual DbSet<CALENDAR_YEDEK3> CALENDAR_YEDEK3 { get; set; }
        public virtual DbSet<CALENDAR_YEDEK4> CALENDAR_YEDEK4 { get; set; }
        public virtual DbSet<FORECAST> FORECAST { get; set; }
        public virtual DbSet<SEASON_AVG_SALES> SEASON_AVG_SALES { get; set; }
        public virtual DbSet<PO_DETAIL_YDK> PO_DETAIL_YDK { get; set; }
    }
}
