//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN
    {
        public int SEASON_ID { get; set; }
        public long SASDETAIL_ID { get; set; }
        public short WEEK { get; set; }
        public decimal QUANTITY { get; set; }
        public int STAGE_ID { get; set; }
        public short YEAR { get; set; }
        public int VERSION_ID { get; set; }
    }
}
