//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_MASTER
    {
        public long ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<long> SEASON_ID { get; set; }
        public Nullable<long> SALES_CHANNEL_ID { get; set; }
        public Nullable<long> PLAN_TYPE_ID { get; set; }
    }
}
