//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_DETAIL_YDK
    {
        public long ID { get; set; }
        public long MASTER_ID { get; set; }
        public long DETAIL_ID { get; set; }
        public Nullable<long> PRODUCT_ID { get; set; }
        public Nullable<long> ASORTI_ID { get; set; }
        public Nullable<long> SUPLLYCHANNEL_ID { get; set; }
        public Nullable<long> SUPPLIER_ID { get; set; }
        public Nullable<long> SALESCHANNEL_ID { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public Nullable<System.DateTime> DUE_DATE_REV { get; set; }
        public Nullable<bool> COMPLETED { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
