//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_WEEK_GROWTH
    {
        public long ID { get; set; }
        public Nullable<long> SEASON_ID { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<long> MERCH_YEAR { get; set; }
        public Nullable<long> MERCH_WEEK { get; set; }
        public Nullable<long> MAINGROUP_ID { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<decimal> PR_WEEK_QTY { get; set; }
        public Nullable<decimal> PR_WEEK_GROWTH1 { get; set; }
    }
}
