//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRO_MEASUREMENT_DETAIL
    {
        public long ID { get; set; }
        public long MASTER_ID { get; set; }
        public string CHAIN { get; set; }
        public decimal HANGERVOLUME { get; set; }
        public decimal HANGERLENGTH { get; set; }
        public decimal HANGERAREA { get; set; }
        public decimal BLOCKVOLUME { get; set; }
        public decimal BLOCKLENGTH { get; set; }
        public decimal BLOCKAREA { get; set; }
    }
}
