//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_LIFE
    {
        public long ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public long MASTER_ID { get; set; }
        public long SEASON_ID { get; set; }
        public long MATERIAL_ENUM_MASTER_ID { get; set; }
        public long ACCOUNT_ENUM_MASTER_ID { get; set; }
        public long MATERIAL_ENUM_VALUE_ID { get; set; }
        public long ACCOUNT_ENUM_VALUE_ID { get; set; }
        public long START_CALENDAR_ID { get; set; }
        public long END_CALENDAR_ID { get; set; }
        public long COMPANY_ID { get; set; }
        public Nullable<int> ORDER_QTY { get; set; }
        public Nullable<int> INI_PLN_QTY { get; set; }
        public Nullable<int> MIN_QTY { get; set; }
        public Nullable<int> MAX_QTY { get; set; }
    }
}
