//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC_INLINE_MASTER
    {
        public long ID { get; set; }
        public long TEDARIKCI_ID { get; set; }
        public System.DateTime TARIH { get; set; }
        public int SEZON_ID { get; set; }
        public long OPTION_ID { get; set; }
        public int SAFHA_ID { get; set; }
        public int USER_ID { get; set; }
    }
}
