//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC_TEST_MASTER
    {
        public long ID { get; set; }
        public Nullable<long> TESTER_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<long> SUPPLIER_ID { get; set; }
        public Nullable<int> RESULT { get; set; }
        public Nullable<int> SEASON_ID { get; set; }
        public long DOMINATOR_ID { get; set; }
        public long CONTROLID { get; set; }
    }
}
