//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class RULE_DETAIL
    {
        public long ID { get; set; }
        public long MASTER_ID { get; set; }
        public int TYPE { get; set; }
        public int PROP_ID { get; set; }
        public long VALUE_ID { get; set; }
        public string UST_VALUE_ID { get; set; }
    }
}
