//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_ACCOUNT_SUMM
    {
        public long ID { get; set; }
        public long ACCOUNT_ID { get; set; }
        public Nullable<long> SEASON_ID { get; set; }
        public long CALENDAR_ID { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> AMOUNT_WO_VAT { get; set; }
        public Nullable<decimal> ISP { get; set; }
        public Nullable<decimal> ISP_WO_VAT { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<int> SALES_DOC_COUNT { get; set; }
        public Nullable<int> RETURN_DOC_COUNT { get; set; }
    }
}
