//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_FACTOR
    {
        public long ID { get; set; }
        public long COMPANY_ID { get; set; }
        public long CALENDAR_ID { get; set; }
        public long MAINGROUP_ID { get; set; }
        public long ROYALTY_ID { get; set; }
        public long STORETYPE_ID { get; set; }
        public decimal FACTOR { get; set; }
    }
}
