//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEASON_SUMM
    {
        public long ID { get; set; }
        public long WH_ID { get; set; }
        public long PRODUCT_ID { get; set; }
        public long ASORTI_ID { get; set; }
        public Nullable<long> ASORTI_DETAIL_ID { get; set; }
        public Nullable<long> SEASON_ID { get; set; }
        public Nullable<decimal> IN_QTY { get; set; }
        public Nullable<decimal> SALES_QTY { get; set; }
        public Nullable<decimal> SALES_L7_QTY { get; set; }
        public Nullable<decimal> INV { get; set; }
        public Nullable<decimal> SHIP_INV { get; set; }
        public Nullable<decimal> RSV_INV { get; set; }
        public Nullable<decimal> OPTION_IN_QTY { get; set; }
        public Nullable<decimal> OPTION_SALES_QTY { get; set; }
        public Nullable<long> FS_DATE { get; set; }
        public Nullable<long> LS_DATE { get; set; }
        public Nullable<decimal> OPTION_INV { get; set; }
        public Nullable<decimal> OPTION_STR_RATIO { get; set; }
    }
}
