//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEASON_AVG_SALES
    {
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<long> SEASON_ID { get; set; }
        public short MERCH_YEAR { get; set; }
        public short MERCH_WEEK { get; set; }
        public Nullable<long> OPTION_ID { get; set; }
        public Nullable<decimal> OPTION_GROWTH { get; set; }
        public Nullable<decimal> OPTION_GROWTH_LFL { get; set; }
        public Nullable<decimal> MODEL_GROWTH_LFL { get; set; }
        public Nullable<decimal> MAINGROUP_GROWTH_LFL { get; set; }
        public Nullable<decimal> UNIT_QTY_OPTION { get; set; }
        public Nullable<decimal> UNIT_QTY_OPTION_LFL { get; set; }
        public Nullable<decimal> UNIT_QTY_MODEL_LFL { get; set; }
        public Nullable<decimal> UNIT_QTY_MAINGROUP_LFL { get; set; }
    }
}
