//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SENDING_LIMIT_MASTER
    {
        public long ID { get; set; }
        public long SEASON_ID { get; set; }
        public long COMPANY_ID { get; set; }
        public int SALES_CHANNEL_ID { get; set; }
        public short PERIOD_TYPE { get; set; }
    }
}
