//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIPMENTS
    {
        public long ID { get; set; }
        public long CALENDAR_ID { get; set; }
        public long SOURCE_WH_ID { get; set; }
        public long TARGET_WH_ID { get; set; }
        public long PRODUCT_ID { get; set; }
        public long ASORTI_ID { get; set; }
        public long SEASON_ID { get; set; }
        public long ACCOUNT_ID { get; set; }
        public long SUPPLIER_ID { get; set; }
        public long SHIPMENT_TYPE_ID { get; set; }
        public Nullable<decimal> GIRIS_MIKTAR { get; set; }
        public Nullable<decimal> CIKIS_MIKTAR { get; set; }
        public Nullable<decimal> BY_SEVK_MIK { get; set; }
        public Nullable<decimal> BY_SEVK_MIK_MGZ { get; set; }
        public Nullable<decimal> BY_MERKEZ_GIRIS_MGZ { get; set; }
        public Nullable<decimal> BY_IADE_MIK_MGZ { get; set; }
        public Nullable<decimal> BY_TRANSFER_CIKIS { get; set; }
        public Nullable<decimal> BY_TRANSFER_GIRIS { get; set; }
        public Nullable<decimal> BY_MRKZ_ARASI_CIKIS_MIK { get; set; }
        public Nullable<decimal> BY_MRKZ_ARASI_GIRIS_MIK { get; set; }
        public Nullable<decimal> BY_SEVK_MIK_SS { get; set; }
        public Nullable<decimal> BY_RMA_KABUL_MIK { get; set; }
        public Nullable<decimal> BY_SATIN_ALMA_GIRIS_MIK { get; set; }
        public Nullable<decimal> BY_TEDARIKCIYE_IADE_MIK { get; set; }
        public Nullable<decimal> BY_DEVANLAY_SEVK_MIK { get; set; }
        public Nullable<decimal> BY_DEVANLAY_IADE_MIK { get; set; }
        public Nullable<decimal> BY_SEVK_MIK_KONSINYE { get; set; }
        public Nullable<decimal> BY_IADE_MIK_KONSINYE { get; set; }
        public Nullable<decimal> BY_KONSINYE_SATIS_MIK { get; set; }
        public Nullable<decimal> BY_KONSINYE_SATISDAN_IADE_MIK { get; set; }
        public Nullable<decimal> BY_STOK_YERI_GIRIS { get; set; }
        public Nullable<decimal> BY_STOK_YERI_CIKIS { get; set; }
        public Nullable<decimal> BY_SEVK_MIK_DIGER { get; set; }
        public Nullable<decimal> BY_GIRIS_MIK_DIGER { get; set; }
    }
}
