//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPLITTINGRULE_MASTER
    {
        public long ID { get; set; }
        public System.DateTime VALIDFOR_BEGIN { get; set; }
        public System.DateTime VALIDFOR_END { get; set; }
        public long RULE_ID { get; set; }
    }
}
