//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORE_RATE
    {
        public long ID { get; set; }
        public Nullable<long> SEASON_ID { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<long> STORE_ID { get; set; }
        public Nullable<long> MAINGROUP_ID { get; set; }
        public Nullable<long> MODEL_ID { get; set; }
        public Nullable<long> OPTION_ID { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<decimal> SR_MAINGROUP { get; set; }
        public Nullable<decimal> SR_MODEL { get; set; }
        public Nullable<decimal> SR_OPTION { get; set; }
    }
}
