//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORE
    {
        public long ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string ADRESS { get; set; }
        public Nullable<long> COUNTY_ID { get; set; }
        public Nullable<long> CITY_ID { get; set; }
        public Nullable<System.DateTime> OPENDATE { get; set; }
        public Nullable<System.DateTime> CLOSEDATE { get; set; }
        public Nullable<long> AREA { get; set; }
        public Nullable<long> SALESCHANNEL_ID { get; set; }
        public Nullable<long> SUBSALESCHANNEL_ID { get; set; }
        public Nullable<long> REGION_ID { get; set; }
        public Nullable<long> SUBREGION_ID { get; set; }
        public Nullable<long> MANAGER_ID { get; set; }
        public Nullable<long> SUBMANAGER_ID { get; set; }
        public Nullable<long> SALESORG_ID { get; set; }
        public Nullable<long> SUBSALESORG_ID { get; set; }
        public Nullable<long> COUNTRY_ID { get; set; }
        public Nullable<long> STORETYPE_ID { get; set; }
        public Nullable<long> STOREBRAND_ID { get; set; }
        public Nullable<long> LOCATIONTYPE_ID { get; set; }
        public Nullable<long> DEFAULT_WH_ID { get; set; }
        public Nullable<long> ATTRIBUTE1_ID { get; set; }
        public Nullable<long> ATTRIBUTE2_ID { get; set; }
        public Nullable<long> ATTRIBUTE3_ID { get; set; }
        public Nullable<long> ATTRIBUTE4_ID { get; set; }
        public Nullable<long> ATTRIBUTE5_ID { get; set; }
        public Nullable<long> ATTRIBUTE6_ID { get; set; }
        public Nullable<long> ATTRIBUTE7_ID { get; set; }
        public Nullable<long> ATTRIBUTE8_ID { get; set; }
        public Nullable<long> ATTRIBUTE9_ID { get; set; }
        public Nullable<long> ATTRIBUTE10_ID { get; set; }
        public Nullable<long> ATTRIBUTE11_ID { get; set; }
        public Nullable<long> ATTRIBUTE12_ID { get; set; }
        public Nullable<long> ATTRIBUTE13_ID { get; set; }
        public Nullable<long> ATTRIBUTE14_ID { get; set; }
        public Nullable<long> ATTRIBUTE15_ID { get; set; }
        public Nullable<long> ATTRIBUTE16_ID { get; set; }
        public Nullable<long> ATTRIBUTE17_ID { get; set; }
        public Nullable<long> ATTRIBUTE18_ID { get; set; }
        public Nullable<long> ATTRIBUTE19_ID { get; set; }
        public Nullable<long> ATTRIBUTE20_ID { get; set; }
        public int CLOSED { get; set; }
        public int NOSHIPMENT { get; set; }
        public int NODELIVERY { get; set; }
    }
}
