//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class STR_PHYSICAL_CPC_MASTER
    {
        public long ID { get; set; }
        public long COMPANY_ID { get; set; }
        public Nullable<long> MATERIAL_ENUM1_MASTER_ID { get; set; }
        public Nullable<long> MATERIAL_ENUM2_MASTER_ID { get; set; }
    }
}
