//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRMTR_COM
    {
        public long ID { get; set; }
        public long OPTION_ID { get; set; }
        public long WH_ID { get; set; }
        public int FORBIDDEN { get; set; }
        public Nullable<int> DST_ID { get; set; }
        public Nullable<System.DateTime> REC_DATE { get; set; }
    }
}
