//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_ACCESSORY
    {
        public long ID { get; set; }
        public Nullable<long> ETL_ID { get; set; }
        public string CODE { get; set; }
        public string ACC_CODE { get; set; }
        public string ACC_DESCRIPTION { get; set; }
        public string ACC_AREA { get; set; }
        public string ACC_TYPE { get; set; }
        public string ACC_SIZES { get; set; }
        public string ACC_BR_GIDER { get; set; }
        public string ACC_GIDER_BR { get; set; }
        public string ACC_PATH { get; set; }
    }
}
