//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_FABRICS
    {
        public long ID { get; set; }
        public Nullable<long> ETL_ID { get; set; }
        public string CODE { get; set; }
        public string FABRIC_CODE { get; set; }
        public string FABRIC_DESCRIPTION { get; set; }
        public string FABRIC_AREA { get; set; }
        public string FABRIC_WEIGHT { get; set; }
        public string FABRIC_WIDTH { get; set; }
        public string FABRIC_TYPE { get; set; }
        public string FABRIC_CONTENT { get; set; }
        public string FABRIC_BR_GIDER { get; set; }
        public string FABRIC_GIDER_BR { get; set; }
        public string FABRIC_PATH { get; set; }
    }
}
