//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_MODELS
    {
        public long ID { get; set; }
        public Nullable<long> ETL_ID { get; set; }
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string CATEGORY { get; set; }
        public string SUBCATEGORY { get; set; }
        public string BRAND { get; set; }
        public string SEASON { get; set; }
        public string STATU { get; set; }
        public string ACTIVITY { get; set; }
        public string UNIVERSE { get; set; }
        public string THEME { get; set; }
        public string ZONE_DEVELOPED_FOR { get; set; }
        public string PLATFORM { get; set; }
        public string GROUP { get; set; }
        public string MATERIAL_COMMERCIAL { get; set; }
        public string COMPOSITION { get; set; }
        public string FIT { get; set; }
        public string PICTURE_PATH1 { get; set; }
        public string PICTURE_PATH2 { get; set; }
        public string CRITICS { get; set; }
    }
}
