//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_PACKAGE
    {
        public long ID { get; set; }
        public Nullable<long> ETL_ID { get; set; }
        public string CODE { get; set; }
        public string PCK_CODE { get; set; }
        public string PCK_DECRIPTION { get; set; }
        public string PCK_AREA { get; set; }
        public string PCK_TYPE { get; set; }
        public string PCK_SIZES { get; set; }
        public string PCK_BR_GIDER { get; set; }
        public string PCK_GIDER_BR { get; set; }
    }
}
