//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_SIZE
    {
        public long ID { get; set; }
        public Nullable<long> ETL_ID { get; set; }
        public string CODE { get; set; }
        public string SIZE_CODE { get; set; }
        public string SIZE_SIZE_GROUP { get; set; }
        public string SIZE_SIZE_NAMES { get; set; }
        public string SIZE_MAIN_SIZE { get; set; }
        public string SIZE_NOTES { get; set; }
        public string SIZE_LABEL { get; set; }
        public string SIZE_SIZE { get; set; }
        public string SIZE_TOL { get; set; }
        public string SIZE_SIZE1 { get; set; }
        public string SIZE_SIZE2 { get; set; }
        public string SIZE_SIZE3 { get; set; }
        public string SIZE_SIZE4 { get; set; }
        public string SIZE_SIZE5 { get; set; }
        public string SIZE_SIZE6 { get; set; }
        public string SIZE_SIZE7 { get; set; }
        public string SIZE_SIZE8 { get; set; }
        public string SIZE_SIZE9 { get; set; }
        public string SIZE_SIZE10 { get; set; }
        public string SIZE_SIZE11 { get; set; }
        public string SIZE_SIZE12 { get; set; }
        public string SIZE_SIZE13 { get; set; }
        public string SIZE_SIZE14 { get; set; }
        public string SIZE_SIZE15 { get; set; }
        public string SIZE_SIZE16 { get; set; }
        public string SIZE_SIZE17 { get; set; }
        public string SIZE_SIZE18 { get; set; }
        public string SIZE_SIZE19 { get; set; }
        public string SIZE_SIZE20 { get; set; }
    }
}
