//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_VARIANT
    {
        public long ID { get; set; }
        public Nullable<long> ETL_ID { get; set; }
        public string CODE { get; set; }
        public string COLOR_VARIATION { get; set; }
        public string MATERIAL { get; set; }
        public string MATERIAL_CODE { get; set; }
        public string GREIGE_CODE { get; set; }
        public string COLOR { get; set; }
        public string SUPPLIER_COLOR { get; set; }
        public string CUST_COLOR { get; set; }
        public string LAB_COLOR { get; set; }
        public string WEIGHT { get; set; }
        public string WEIGHT_UNIT { get; set; }
    }
}
