//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNITASSIGMENT_DETAIL
    {
        public long ID { get; set; }
        public long MASTER_ID { get; set; }
        public long RULE_DETAIL_ID { get; set; }
        public long UNIT_ID { get; set; }
        public int ACTIVE_COUNT { get; set; }
        public int PASSIVE_COUNT { get; set; }
    }
}
