//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class WH
    {
        public long ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string ADRESS { get; set; }
        public Nullable<long> COUNTY_ID { get; set; }
        public Nullable<long> CITY_ID { get; set; }
        public Nullable<long> WH_TYPE_ID { get; set; }
        public Nullable<long> WH_STYLE_ID { get; set; }
        public Nullable<long> CENTER { get; set; }
        public Nullable<long> ACCOUNT_ID { get; set; }
        public Nullable<long> ATTRIBUTE1_ID { get; set; }
        public Nullable<long> ATTRIBUTE2_ID { get; set; }
        public Nullable<long> ATTRIBUTE3_ID { get; set; }
        public Nullable<long> ATTRIBUTE4_ID { get; set; }
        public Nullable<long> ATTRIBUTE5_ID { get; set; }
        public Nullable<long> ATTRIBUTE6_ID { get; set; }
        public Nullable<long> ATTRIBUTE7_ID { get; set; }
        public Nullable<long> ATTRIBUTE8_ID { get; set; }
        public Nullable<long> ATTRIBUTE9_ID { get; set; }
        public Nullable<long> ATTRIBUTE10_ID { get; set; }
    }
}
