//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public long ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public System.DateTime DOCUMENT_DATE { get; set; }
        public long DOCUMENT_TYPE { get; set; }
    }
}
