//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long ID { get; set; }
        public long ACCOUNT_ID { get; set; }
        public long PRODUCT_ID { get; set; }
        public System.DateTime TRANSACTION_DATE { get; set; }
        public long TRANSACTION_TYPE { get; set; }
        public int DIRECTION { get; set; }
    }
}
