//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_customer_affiliate
    {
        public int customer_id { get; set; }
        public string company { get; set; }
        public string website { get; set; }
        public string tracking { get; set; }
        public decimal commission { get; set; }
        public string tax { get; set; }
        public string payment { get; set; }
        public string cheque { get; set; }
        public string paypal { get; set; }
        public string bank_name { get; set; }
        public string bank_branch_number { get; set; }
        public string bank_swift_code { get; set; }
        public string bank_account_name { get; set; }
        public string bank_account_number { get; set; }
        public string custom_field { get; set; }
        public bool status { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
