//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_customer
    {
        public int customer_id { get; set; }
        public int customer_group_id { get; set; }
        public int store_id { get; set; }
        public int language_id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string fax { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public string cart { get; set; }
        public string wishlist { get; set; }
        public bool newsletter { get; set; }
        public int address_id { get; set; }
        public string custom_field { get; set; }
        public string ip { get; set; }
        public bool status { get; set; }
        public bool safe { get; set; }
        public string token { get; set; }
        public string code { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
