//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_coupon
    {
        public int coupon_id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string type { get; set; }
        public decimal discount { get; set; }
        public bool logged { get; set; }
        public bool shipping { get; set; }
        public decimal total { get; set; }
        public System.DateTime date_start { get; set; }
        public System.DateTime date_end { get; set; }
        public int uses_total { get; set; }
        public string uses_customer { get; set; }
        public bool status { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
