//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_event
    {
        public int event_id { get; set; }
        public string code { get; set; }
        public string trigger { get; set; }
        public string action { get; set; }
        public bool status { get; set; }
        public int sort_order { get; set; }
    }
}
