//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_journal2_blog_category
    {
        public int category_id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string image { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> sort_order { get; set; }
    }
}
