//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_layout_route
    {
        public int layout_route_id { get; set; }
        public int layout_id { get; set; }
        public int store_id { get; set; }
        public string route { get; set; }
    }
}
