//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_modification
    {
        public int modification_id { get; set; }
        public int extension_install_id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string author { get; set; }
        public string version { get; set; }
        public string link { get; set; }
        public string xml { get; set; }
        public bool status { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
