//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_order_voucher
    {
        public int order_voucher_id { get; set; }
        public int order_id { get; set; }
        public int voucher_id { get; set; }
        public string description { get; set; }
        public string code { get; set; }
        public string from_name { get; set; }
        public string from_email { get; set; }
        public string to_name { get; set; }
        public string to_email { get; set; }
        public int voucher_theme_id { get; set; }
        public string message { get; set; }
        public decimal amount { get; set; }
    }
}
