//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_order_total
    {
        public int order_total_id { get; set; }
        public int order_id { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public decimal value { get; set; }
        public int sort_order { get; set; }
    }
}
