//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_order_history
    {
        public int order_history_id { get; set; }
        public int order_id { get; set; }
        public int order_status_id { get; set; }
        public bool notify { get; set; }
        public string comment { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
