//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_review
    {
        public int review_id { get; set; }
        public int product_id { get; set; }
        public int customer_id { get; set; }
        public string author { get; set; }
        public string text { get; set; }
        public int rating { get; set; }
        public bool status { get; set; }
        public System.DateTime date_added { get; set; }
        public System.DateTime date_modified { get; set; }
    }
}
