//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_download_description
    {
        public int download_id { get; set; }
        public int language_id { get; set; }
        public string name { get; set; }
    }
}
