//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_return
    {
        public int return_id { get; set; }
        public int order_id { get; set; }
        public int product_id { get; set; }
        public int customer_id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string product { get; set; }
        public string model { get; set; }
        public int quantity { get; set; }
        public bool opened { get; set; }
        public int return_reason_id { get; set; }
        public int return_action_id { get; set; }
        public int return_status_id { get; set; }
        public string comment { get; set; }
        public System.DateTime date_ordered { get; set; }
        public System.DateTime date_added { get; set; }
        public System.DateTime date_modified { get; set; }
    }
}
