//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_recurring
    {
        public int recurring_id { get; set; }
        public decimal price { get; set; }
        public string frequency { get; set; }
        public long duration { get; set; }
        public long cycle { get; set; }
        public sbyte trial_status { get; set; }
        public decimal trial_price { get; set; }
        public string trial_frequency { get; set; }
        public long trial_duration { get; set; }
        public long trial_cycle { get; set; }
        public sbyte status { get; set; }
        public int sort_order { get; set; }
    }
}
