//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_setting
    {
        public int setting_id { get; set; }
        public int store_id { get; set; }
        public string code { get; set; }
        public string key { get; set; }
        public string value { get; set; }
        public bool serialized { get; set; }
    }
}
