//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyEntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_voucher_history
    {
        public int voucher_history_id { get; set; }
        public int voucher_id { get; set; }
        public int order_id { get; set; }
        public decimal amount { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
