//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtyIntegrations.n11CityService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.n11.com/ws/schemas", ConfigurationName="n11CityService.CityServicePort")]
    public interface CityServicePort {
        
        // CODEGEN: Generating message contract since the operation GetCities is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BtyIntegrations.n11CityService.GetCitiesResponse1 GetCities(BtyIntegrations.n11CityService.GetCitiesRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BtyIntegrations.n11CityService.GetCitiesResponse1> GetCitiesAsync(BtyIntegrations.n11CityService.GetCitiesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetCity is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BtyIntegrations.n11CityService.GetCityResponse1 GetCity(BtyIntegrations.n11CityService.GetCityRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BtyIntegrations.n11CityService.GetCityResponse1> GetCityAsync(BtyIntegrations.n11CityService.GetCityRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetDistrict is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BtyIntegrations.n11CityService.GetDistrictResponse1 GetDistrict(BtyIntegrations.n11CityService.GetDistrictRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BtyIntegrations.n11CityService.GetDistrictResponse1> GetDistrictAsync(BtyIntegrations.n11CityService.GetDistrictRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetNeighborhoods is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BtyIntegrations.n11CityService.GetNeighborhoodsResponse1 GetNeighborhoods(BtyIntegrations.n11CityService.GetNeighborhoodsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BtyIntegrations.n11CityService.GetNeighborhoodsResponse1> GetNeighborhoodsAsync(BtyIntegrations.n11CityService.GetNeighborhoodsRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetCitiesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class NeighborhoodData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class DistrictData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class CityData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cityCodeField;
        
        private long cityIdField;
        
        private string cityNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
                this.RaisePropertyChanged("cityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long cityId {
            get {
                return this.cityIdField;
            }
            set {
                this.cityIdField = value;
                this.RaisePropertyChanged("cityId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
                this.RaisePropertyChanged("cityName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ResultInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private string errorCategoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string errorCategory {
            get {
                return this.errorCategoryField;
            }
            set {
                this.errorCategoryField = value;
                this.RaisePropertyChanged("errorCategory");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetCitiesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private CityData[] citiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("city", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CityData[] cities {
            get {
                return this.citiesField;
            }
            set {
                this.citiesField = value;
                this.RaisePropertyChanged("cities");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public BtyIntegrations.n11CityService.GetCitiesRequest GetCitiesRequest;
        
        public GetCitiesRequest1() {
        }
        
        public GetCitiesRequest1(BtyIntegrations.n11CityService.GetCitiesRequest GetCitiesRequest) {
            this.GetCitiesRequest = GetCitiesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public BtyIntegrations.n11CityService.GetCitiesResponse GetCitiesResponse;
        
        public GetCitiesResponse1() {
        }
        
        public GetCitiesResponse1(BtyIntegrations.n11CityService.GetCitiesResponse GetCitiesResponse) {
            this.GetCitiesResponse = GetCitiesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetCityRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cityCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string cityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
                this.RaisePropertyChanged("cityCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetCityResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private CityData cityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public CityData city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public BtyIntegrations.n11CityService.GetCityRequest GetCityRequest;
        
        public GetCityRequest1() {
        }
        
        public GetCityRequest1(BtyIntegrations.n11CityService.GetCityRequest GetCityRequest) {
            this.GetCityRequest = GetCityRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public BtyIntegrations.n11CityService.GetCityResponse GetCityResponse;
        
        public GetCityResponse1() {
        }
        
        public GetCityResponse1(BtyIntegrations.n11CityService.GetCityResponse GetCityResponse) {
            this.GetCityResponse = GetCityResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetDistrictRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cityCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string cityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
                this.RaisePropertyChanged("cityCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetDistrictResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private DistrictData[] districtsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("district", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DistrictData[] districts {
            get {
                return this.districtsField;
            }
            set {
                this.districtsField = value;
                this.RaisePropertyChanged("districts");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistrictRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public BtyIntegrations.n11CityService.GetDistrictRequest GetDistrictRequest;
        
        public GetDistrictRequest1() {
        }
        
        public GetDistrictRequest1(BtyIntegrations.n11CityService.GetDistrictRequest GetDistrictRequest) {
            this.GetDistrictRequest = GetDistrictRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistrictResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public BtyIntegrations.n11CityService.GetDistrictResponse GetDistrictResponse;
        
        public GetDistrictResponse1() {
        }
        
        public GetDistrictResponse1(BtyIntegrations.n11CityService.GetDistrictResponse GetDistrictResponse) {
            this.GetDistrictResponse = GetDistrictResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetNeighborhoodsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long districtIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long districtId {
            get {
                return this.districtIdField;
            }
            set {
                this.districtIdField = value;
                this.RaisePropertyChanged("districtId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetNeighborhoodsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private NeighborhoodData[] neighborhoodsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("neighborhood", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public NeighborhoodData[] neighborhoods {
            get {
                return this.neighborhoodsField;
            }
            set {
                this.neighborhoodsField = value;
                this.RaisePropertyChanged("neighborhoods");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNeighborhoodsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public BtyIntegrations.n11CityService.GetNeighborhoodsRequest GetNeighborhoodsRequest;
        
        public GetNeighborhoodsRequest1() {
        }
        
        public GetNeighborhoodsRequest1(BtyIntegrations.n11CityService.GetNeighborhoodsRequest GetNeighborhoodsRequest) {
            this.GetNeighborhoodsRequest = GetNeighborhoodsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNeighborhoodsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public BtyIntegrations.n11CityService.GetNeighborhoodsResponse GetNeighborhoodsResponse;
        
        public GetNeighborhoodsResponse1() {
        }
        
        public GetNeighborhoodsResponse1(BtyIntegrations.n11CityService.GetNeighborhoodsResponse GetNeighborhoodsResponse) {
            this.GetNeighborhoodsResponse = GetNeighborhoodsResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CityServicePortChannel : BtyIntegrations.n11CityService.CityServicePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CityServicePortClient : System.ServiceModel.ClientBase<BtyIntegrations.n11CityService.CityServicePort>, BtyIntegrations.n11CityService.CityServicePort {
        
        public CityServicePortClient() {
        }
        
        public CityServicePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CityServicePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CityServicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CityServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BtyIntegrations.n11CityService.GetCitiesResponse1 BtyIntegrations.n11CityService.CityServicePort.GetCities(BtyIntegrations.n11CityService.GetCitiesRequest1 request) {
            return base.Channel.GetCities(request);
        }
        
        public BtyIntegrations.n11CityService.GetCitiesResponse GetCities(BtyIntegrations.n11CityService.GetCitiesRequest GetCitiesRequest) {
            BtyIntegrations.n11CityService.GetCitiesRequest1 inValue = new BtyIntegrations.n11CityService.GetCitiesRequest1();
            inValue.GetCitiesRequest = GetCitiesRequest;
            BtyIntegrations.n11CityService.GetCitiesResponse1 retVal = ((BtyIntegrations.n11CityService.CityServicePort)(this)).GetCities(inValue);
            return retVal.GetCitiesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BtyIntegrations.n11CityService.GetCitiesResponse1> BtyIntegrations.n11CityService.CityServicePort.GetCitiesAsync(BtyIntegrations.n11CityService.GetCitiesRequest1 request) {
            return base.Channel.GetCitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BtyIntegrations.n11CityService.GetCitiesResponse1> GetCitiesAsync(BtyIntegrations.n11CityService.GetCitiesRequest GetCitiesRequest) {
            BtyIntegrations.n11CityService.GetCitiesRequest1 inValue = new BtyIntegrations.n11CityService.GetCitiesRequest1();
            inValue.GetCitiesRequest = GetCitiesRequest;
            return ((BtyIntegrations.n11CityService.CityServicePort)(this)).GetCitiesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BtyIntegrations.n11CityService.GetCityResponse1 BtyIntegrations.n11CityService.CityServicePort.GetCity(BtyIntegrations.n11CityService.GetCityRequest1 request) {
            return base.Channel.GetCity(request);
        }
        
        public BtyIntegrations.n11CityService.GetCityResponse GetCity(BtyIntegrations.n11CityService.GetCityRequest GetCityRequest) {
            BtyIntegrations.n11CityService.GetCityRequest1 inValue = new BtyIntegrations.n11CityService.GetCityRequest1();
            inValue.GetCityRequest = GetCityRequest;
            BtyIntegrations.n11CityService.GetCityResponse1 retVal = ((BtyIntegrations.n11CityService.CityServicePort)(this)).GetCity(inValue);
            return retVal.GetCityResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BtyIntegrations.n11CityService.GetCityResponse1> BtyIntegrations.n11CityService.CityServicePort.GetCityAsync(BtyIntegrations.n11CityService.GetCityRequest1 request) {
            return base.Channel.GetCityAsync(request);
        }
        
        public System.Threading.Tasks.Task<BtyIntegrations.n11CityService.GetCityResponse1> GetCityAsync(BtyIntegrations.n11CityService.GetCityRequest GetCityRequest) {
            BtyIntegrations.n11CityService.GetCityRequest1 inValue = new BtyIntegrations.n11CityService.GetCityRequest1();
            inValue.GetCityRequest = GetCityRequest;
            return ((BtyIntegrations.n11CityService.CityServicePort)(this)).GetCityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BtyIntegrations.n11CityService.GetDistrictResponse1 BtyIntegrations.n11CityService.CityServicePort.GetDistrict(BtyIntegrations.n11CityService.GetDistrictRequest1 request) {
            return base.Channel.GetDistrict(request);
        }
        
        public BtyIntegrations.n11CityService.GetDistrictResponse GetDistrict(BtyIntegrations.n11CityService.GetDistrictRequest GetDistrictRequest) {
            BtyIntegrations.n11CityService.GetDistrictRequest1 inValue = new BtyIntegrations.n11CityService.GetDistrictRequest1();
            inValue.GetDistrictRequest = GetDistrictRequest;
            BtyIntegrations.n11CityService.GetDistrictResponse1 retVal = ((BtyIntegrations.n11CityService.CityServicePort)(this)).GetDistrict(inValue);
            return retVal.GetDistrictResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BtyIntegrations.n11CityService.GetDistrictResponse1> BtyIntegrations.n11CityService.CityServicePort.GetDistrictAsync(BtyIntegrations.n11CityService.GetDistrictRequest1 request) {
            return base.Channel.GetDistrictAsync(request);
        }
        
        public System.Threading.Tasks.Task<BtyIntegrations.n11CityService.GetDistrictResponse1> GetDistrictAsync(BtyIntegrations.n11CityService.GetDistrictRequest GetDistrictRequest) {
            BtyIntegrations.n11CityService.GetDistrictRequest1 inValue = new BtyIntegrations.n11CityService.GetDistrictRequest1();
            inValue.GetDistrictRequest = GetDistrictRequest;
            return ((BtyIntegrations.n11CityService.CityServicePort)(this)).GetDistrictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BtyIntegrations.n11CityService.GetNeighborhoodsResponse1 BtyIntegrations.n11CityService.CityServicePort.GetNeighborhoods(BtyIntegrations.n11CityService.GetNeighborhoodsRequest1 request) {
            return base.Channel.GetNeighborhoods(request);
        }
        
        public BtyIntegrations.n11CityService.GetNeighborhoodsResponse GetNeighborhoods(BtyIntegrations.n11CityService.GetNeighborhoodsRequest GetNeighborhoodsRequest) {
            BtyIntegrations.n11CityService.GetNeighborhoodsRequest1 inValue = new BtyIntegrations.n11CityService.GetNeighborhoodsRequest1();
            inValue.GetNeighborhoodsRequest = GetNeighborhoodsRequest;
            BtyIntegrations.n11CityService.GetNeighborhoodsResponse1 retVal = ((BtyIntegrations.n11CityService.CityServicePort)(this)).GetNeighborhoods(inValue);
            return retVal.GetNeighborhoodsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BtyIntegrations.n11CityService.GetNeighborhoodsResponse1> BtyIntegrations.n11CityService.CityServicePort.GetNeighborhoodsAsync(BtyIntegrations.n11CityService.GetNeighborhoodsRequest1 request) {
            return base.Channel.GetNeighborhoodsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BtyIntegrations.n11CityService.GetNeighborhoodsResponse1> GetNeighborhoodsAsync(BtyIntegrations.n11CityService.GetNeighborhoodsRequest GetNeighborhoodsRequest) {
            BtyIntegrations.n11CityService.GetNeighborhoodsRequest1 inValue = new BtyIntegrations.n11CityService.GetNeighborhoodsRequest1();
            inValue.GetNeighborhoodsRequest = GetNeighborhoodsRequest;
            return ((BtyIntegrations.n11CityService.CityServicePort)(this)).GetNeighborhoodsAsync(inValue);
        }
    }
}
